---
# Per environment values which override defaults in hmpps-education-employment-api/values.yaml

generic-service:
  ingress:
    host: education-employment-api.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    API_BASE_URL_OAUTH: https://sign-in.hmpps.service.justice.gov.uk/auth

  # Enable syncing the production database to pre-prod. This creates a scheduled job that runs every 4 hours, and will
  # restore the database to pre-prod if that is a newer version of the database since the last restore.
  postgresDatabaseRestore:
    enabled: true
    namespace_secrets:
      edu-rds-instance-output:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      rds-postgresql-instance-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: education-alerts
